# General Jekyll Config
pygments: true
url: http://landonmarder.com/
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore]

# Theme customization - please change from the defaults!
theme:
  # Color for top bar, links, etc
  highlight_color: '#3498db'
  hover_color: '#79B7E1'

  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: landonmarder
    #bitbucket: philipj
    hacker_news: reyvantiki
    #stackexchange: 348619
    #stackoverflow: 348619
    twitter: landonmarder
    #facebook: zuck
    #tumblr: animalygifs
    linkedin: landonmarder
    #gplus: 110552447039675960964

  # "Hi, I'm _______"
  name: Landon Marder
  email: landon.marder@gmail.com
  tagline: "Web developer in NYC."

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-xxxx-x

  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: false
