# Site settings
title:       Landon Marder
email:       landon.marder@gmail.com
author:      Landon Marder
description: "Landon Marder is a web developer in NYC."
baseurl:     ""
url:         "http://www.landonmarder.com"

# Google analytics
google_analytics: UA-50757512-1

# Optional features
animated:           true
show_related_posts: false
show_post_footers:  false

# Social icons
show_social_icons: true
github_username: landonmarder
twitter_username: landonmarder
google_plus_id:
linkedin_username: landonmarder
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     kramdown
permalink:    pretty
paginate:     3
sass:
  compressed: true
